### ISSUE TITLE
run_indiv.py fails

### ISSUE THREAD

**Issue by gabora** [damienArnol/svca#5]
I managed to submit the jobs by run_all_cluster.py, but got an error:

from the log file: 
ag252714@cluster:~/svca/SVCA/svca/run_cluster[659]$ vim tmp_log 

Traceback (most recent call last):
  File "../run/run_indiv.py", line 59, in <module>
    run(data_dir, protein_index, output_dir, normalisation)
  File "../run/run_indiv.py", line 36, in run
    model = Model1(phenotype, X, norm=normalisation, oos_predictions=0., cov_terms=cterms, kin_from=kin_from, cv_ix=0)
  File "/home/ag252714/.local/lib/python2.7/site-packages/svca/models/model1.py", line 49, in __init__
    self.init_model(cov_terms)
  File "/home/ag252714/.local/lib/python2.7/site-packages/svca/models/model_base.py", line 84, in init_model
    self.build_cov(cov_terms)
  File "/home/ag252714/.local/lib/python2.7/site-packages/svca/models/model1.py", line 81, in build_cov
    self.covar = apply(SumCov, self.covar_terms.values())
  File "/home/ag252714/.local/lib/python2.7/site-packages/limix/core/covar/combinators.py", line 22, in __init__
    self.addCovariance(covar)
  File "/home/ag252714/.local/lib/python2.7/site-packages/limix/core/covar/acombinators.py", line 22, in addCovariance
    assert covar.dim==self.dim, 'Dimension mismatch.'
  File "/home/ag252714/.local/lib/python2.7/site-packages/limix/core/covar/zkz.py", line 46, in dim
    return self.K().shape[0]
  File "/home/ag252714/.local/lib/python2.7/site-packages/limix/hcache/_hcache.py", line 173, in method_wrapper
    result = method(self, *args, **kwargs)
  File "/home/ag252714/.local/lib/python2.7/site-packages/limix/core/covar/zkz.py", line 180, in K
    K = self._K()
  File "/home/ag252714/.local/lib/python2.7/site-packages/limix/hcache/_hcache.py", line 173, in method_wrapper
    result = method(self, *args, **kwargs)
  File "/home/ag252714/.local/lib/python2.7/site-packages/limix/core/covar/zkz.py", line 224, in _K
    z = self.se.K()
  File "/home/ag252714/.local/lib/python2.7/site-packages/limix/hcache/_hcache.py", line 173, in method_wrapper
    result = method(self, *args, **kwargs)
  File "/home/ag252714/.local/lib/python2.7/site-packages/limix/core/covar/sqexp.py", line 194, in K
    return self.scale * sp.exp(-self.E()/(2*self.length))
  File "/home/ag252714/.local/lib/python2.7/site-packages/limix/hcache/_hcache.py", line 173, in method_wrapper
    result = method(self, *args, **kwargs)
  File "/home/ag252714/.local/lib/python2.7/site-packages/limix/core/covar/sqexp.py", line 183, in E
    rv = SS.distance.pdist(self.X,'euclidean')**2.
  File "/usr/lib64/python2.7/site-packages/scipy/spatial/distance.py", line 1176, in pdist
    dm = np.zeros((m * (m - 1) / 2,), dtype=np.double)
TypeError: 'float' object cannot be interpreted as an index

**Comment by gabora** [comment]
Ok, so the issue here was a very old scipy  version (0.0.12) on the cluster.
Code runs with newer version, tested with scipy v1.1.0.

I guess we could close this issue
